/**
 * Base de datos oficial de Asignaturas de 1º de Ingeniería del Software (Plan 2023)
 * Escuela Técnica Superior de Ingeniería Informática - Universidad de Málaga (UMA)
 * 
 * Enlaces verificados a los mejores apuntes gratuitos de Wuolah (mayor valoración,
 * más completos y sin enlaces rotos ni plantillas genéricas).
 * Optimizados para abrir y descargar directamente en Wuolah.
 */

const SUBJECTS_DATA = [
  // ==========================================
  // PRIMER SEMESTRE
  // ==========================================
  {
    id: "101",
    code: "101",
    name: "Fundamentos de Electrónica",
    acronym: "FEl",
    semester: 1,
    ects: 6,
    type: "Formación Básica",
    category: "hardware",
    difficulty: "Alta",
    passRate: "58%",
    color: "#f59e0b",
    icon: "zap",
    umaGuideUrl: "https://www.uma.es/etsi-informatica/",
    summary: "Estudio de las señales eléctricas, física de semiconductores, componentes analógicos y diseño básico de puertas lógicas electrónicas que sustentan los computadores.",
    topics: [
      "Señales analógicas y digitales, análisis de circuitos en régimen permanente",
      "Dispositivos semiconductores: Diodos de unión PN, rectificadores, diodos Zener",
      "Transistores de Unión Bipolar (BJT): Polarización, recta de carga y amplificación",
      "Transistores de Efecto de Campo (MOSFET): Comportamiento como interruptor y lógica CMOS",
      "Amplificadores Operacionales (AmpOp): Configuraciones inversora, no inversora, sumador y comparador",
      "Familias lógicas y circuitos electrónicos de conmutación"
    ],
    examTips: "Los ejercicios con amplificadores operacionales y el cálculo del punto de operación (Q) en BJT/MOSFET caen siempre en los parciales. Asegúrate de verificar siempre si el transistor está en zona activa o saturación.",
    wuolahSearchQuery: "Fundamentos de Electrónica UMA Grado Informatica Software",
    wuolahDirectUrl: "https://wuolah.com/apuntes/fundamentos-de-electronica?communityId=13891&f_course=1",
    bestWuolahNotes: [
      {
        id: "fel-01",
        wuolahUrl: "https://wuolah.com/apuntes/fundamentos-de-electronica/relacion-tema-7-resuelta-pdf-11340867",
        title: "Relación Tema 7 Resuelta - Amplificadores Operacionales y Filtros",
        rating: 4.9,
        reviewsCount: 59,
        downloads: "32",
        pages: 8,
        type: "Ejercicios Resueltos",
        badge: "Top Valoración",
        uploader: "ana_alfzurbano6",
        isFree: true,
        description: "Relación oficial de problemas del Tema 7 resuelta paso a paso: circuitos con AmpOp inversores, no inversores y cálculo analítico de ganancias de tensión sin omisión de pasos.",
        searchWuolahTerm: "Fundamentos Electronica relacion tema 7 resuelta ana_alfzurbano6"
      },
      {
        id: "fel-02",
        wuolahUrl: "https://wuolah.com/apuntes/fundamentos-de-electronica/practica-bipolar-pdf-11445590",
        title: "Práctica Transistores Bipolares (BJT) - Memoria Completa y Cálculos",
        rating: 4.9,
        reviewsCount: 125,
        downloads: "17",
        pages: 14,
        type: "Práctica Completa",
        badge: "Guía de Laboratorio",
        uploader: "nick_404",
        isFree: true,
        description: "Memoria completa de prácticas de laboratorio sobre transistores BJT: recta de carga estática, punto de trabajo Q, mediciones osciloscópicas y respuestas a cuestiones de evaluación.",
        searchWuolahTerm: "Practica Bipolar nick_404 fundamentos electronica uma"
      },
      {
        id: "fel-03",
        wuolahUrl: "https://wuolah.com/apuntes/fundamentos-de-electronica/practica-mosfet-pdf-11445596",
        title: "Práctica Transistores MOSFET - Conmutación y Curvas Características",
        rating: 4.8,
        reviewsCount: 113,
        downloads: "17",
        pages: 21,
        type: "Práctica Completa",
        badge: "Muy Completo",
        uploader: "nick_404",
        isFree: true,
        description: "Guía exhaustiva de 21 páginas con el estudio de transistores de efecto de campo MOSFET: zonas de corte, lineal y saturación, tablas de valores y gráficas comparativas.",
        searchWuolahTerm: "Practica MOSFET nick_404 fundamentos electronica"
      }
    ]
  },
  {
    id: "102",
    code: "102",
    name: "Fundamentos Físicos de la Informática",
    acronym: "FFI",
    semester: 1,
    ects: 6,
    type: "Formación Básica",
    category: "hardware",
    difficulty: "Muy Alta",
    passRate: "49%",
    color: "#ef4444",
    icon: "atom",
    umaGuideUrl: "https://www.uma.es/etsi-informatica/",
    summary: "Bases del electromagnetismo, teoría de campos, electrodinámica y principios cuánticos aplicados a semiconductores y soportes de almacenamiento digital.",
    topics: [
      "Campo electrostático en el vacío y en medios materiales: Ley de Coulomb y Teorema de Gauss",
      "Potencial electrostático, energía y capacidad: Condensadores con dieléctricos",
      "Corriente eléctrica estacionaria: Ley de Ohm microscópica y circuitos de continua",
      "Campo magnético e inducción electromagnética: Ley de Biot-Savart, Ampère y Faraday-Lenz",
      "Ondas electromagnéticas y su propagación en medios de transmisión",
      "Fundamentos físicos de la teoría de bandas y dispositivos de estado sólido"
    ],
    examTips: "El Teorema de Gauss en cilindros/esferas coaxiales y los problemas de inducción (Ley de Faraday-Lenz) son obligatorios. Dibuja siempre el vector superficie y justifica la dirección de la fem inducida.",
    wuolahSearchQuery: "Fundamentos Fisicos de la Informatica FFI UMA Wuolah",
    wuolahDirectUrl: "https://wuolah.com/apuntes/fundamentos-fisicos-de-la-informatica?communityId=13891&f_course=1",
    bestWuolahNotes: [
      {
        id: "ffi-01",
        wuolahUrl: "https://wuolah.com/apuntes/fundamentos-fisicos-de-la-informatica/formulario-pdf-12568903",
        title: "Formulario Maestro Oficial FFI con Todas las Ecuaciones y Unidades",
        rating: 5.0,
        reviewsCount: 145,
        downloads: "57",
        pages: 2,
        type: "Formulario",
        badge: "Imprescindible",
        uploader: "artina",
        isFree: true,
        description: "Contiene TODAS las fórmulas de electrostática, magnetismo, Gauss e inducción con sus nombres, constantes físicas y unidades de medida del Sistema Internacional para examen.",
        searchWuolahTerm: "Formulario FFI artina fisica uma"
      },
      {
        id: "ffi-02",
        wuolahUrl: "https://wuolah.com/apuntes/fundamentos-fisicos-de-la-informatica/ejercicios-temario-completo-2-ejercicios-campo-magne-tico-pdf-12568892",
        title: "Colección de Ejercicios del Temario Completo y Campo Magnético",
        rating: 4.9,
        reviewsCount: 136,
        downloads: "77",
        pages: 12,
        type: "Problemas Resueltos",
        badge: "Más Descargado",
        uploader: "artina",
        isFree: true,
        description: "El recopilatorio más popular de problemas de examen desarrollados: espiras en movimiento, transitorios RC, dipolos y fuerzas de Lorentz explicadas con esquemas vectoriales.",
        searchWuolahTerm: "Ejercicios temario completo campo magnetico artina ffi"
      },
      {
        id: "ffi-03",
        wuolahUrl: "https://wuolah.com/apuntes/fundamentos-fisicos-de-la-informatica/examen-septiembre-23-resuelto-pdf-12569050",
        title: "Examen Oficial Septiembre 2023 Resuelto con Justificaciones",
        rating: 4.9,
        reviewsCount: 94,
        downloads: "28",
        pages: 3,
        type: "Examen Resuelto",
        badge: "Examen Convocatoria",
        uploader: "artina",
        isFree: true,
        description: "Convocatoria oficial extraordinaria de septiembre resuelta íntegramente con desarrollos matemáticos rigurosos, cálculos de flujo magnético y comprobación dimensional.",
        searchWuolahTerm: "Examen septiembre 2023 resuelto artina ffi uma"
      }
    ]
  },
  {
    id: "103",
    code: "103",
    name: "Introducción a la Programación",
    acronym: "IP",
    semester: 1,
    ects: 6,
    type: "Formación Básica",
    category: "software",
    difficulty: "Media",
    passRate: "65%",
    color: "#3b82f6",
    icon: "code",
    umaGuideUrl: "https://www.uma.es/etsi-informatica/",
    summary: "Fundamentos de la programación imperativa y estructurada. Diseño de algoritmos, estructuras de control, funciones, tipos estructurados y gestión de memoria estática y dinámica en C/C++.",
    topics: [
      "Algoritmos, diagramas de flujo y entorno de programación",
      "Tipos de datos básicos, operadores, expresiones y conversiones",
      "Estructuras de control: Selección (if, switch) y repetición (while, for, do-while)",
      "Modularidad: Diseño de funciones, paso por valor y por referencia",
      "Estructuras de datos agregadas: Vectores, matrices y cadenas de caracteres",
      "Registros (structs) y punteros: Introducción a la memoria dinámica",
      "Recursividad básica y algoritmos clásicos de búsqueda y ordenación"
    ],
    examTips: "Cuidado con los casos límite en bucles (arrays fuera de rango por 1 índice). En el examen de laboratorio en ordenador, compila con warnings activados (-Wall) para evitar fallos de memoria.",
    wuolahSearchQuery: "Introducción Programación Fundamentos Programacion UMA Wuolah",
    wuolahDirectUrl: "https://wuolah.com/apuntes/fundamentos-de-la-programacion?communityId=13891&f_course=1",
    bestWuolahNotes: [
      {
        id: "ip-01",
        wuolahUrl: "https://wuolah.com/apuntes/fundamentos-de-la-programacion/examenes-finales-15-septiembre-2023-pdf-11355458",
        title: "Recopilatorio de Exámenes Finales Oficiales de la Sala Común",
        rating: 5.0,
        reviewsCount: 108,
        downloads: "99",
        pages: 15,
        type: "Exámenes Resueltos",
        badge: "Top Examen",
        uploader: "darchery",
        isFree: true,
        description: "Compendio de 15 exámenes oficiales de la sala común de la ETSI Informática con soluciones en C++, tratamiento de arrays bidimensionales y estructuras de datos dinámicas.",
        searchWuolahTerm: "Examenes finales sala comun darchery programacion uma"
      },
      {
        id: "ip-02",
        wuolahUrl: "https://wuolah.com/apuntes/fundamentos-de-la-programacion/febrero-2021-ejercicio-2-cpp-9671328",
        title: "Examen Convocatoria Ordinaria Resuelto y Comentado en C++",
        rating: 4.9,
        reviewsCount: 164,
        downloads: "143",
        pages: 6,
        type: "Examen y Código",
        badge: "Más Descargado",
        uploader: "Javierub",
        isFree: true,
        description: "Código fuente completo y depurado del ejercicio principal de examen, detallando la lógica de punteros, paso por referencia y tratamiento de ficheros.",
        searchWuolahTerm: "Febrero 2021 ejercicio 2 cpp Javierub programacion"
      },
      {
        id: "ip-03",
        wuolahUrl: "https://wuolah.com/apuntes/fundamentos-de-la-programacion/problemas-control-1-octubre-2024-pdf-11172765",
        title: "Problemas Control 1 Reciente Resueltos con Casos de Prueba",
        rating: 4.8,
        reviewsCount: 97,
        downloads: "100",
        pages: 5,
        type: "Controles Parciales",
        badge: "Reciente 2024",
        uploader: "oscardonoso",
        isFree: true,
        description: "Resolución del primer control parcial: condicionales anidados, bucles acumuladores y funciones con validación exhaustiva de precondiciones y postcondiciones.",
        searchWuolahTerm: "Problemas control 1 octubre 2024 oscardonoso programacion"
      }
    ]
  },
  {
    id: "104",
    code: "104",
    name: "Matemática Discreta",
    acronym: "MD",
    semester: 1,
    ects: 6,
    type: "Formación Básica",
    category: "math",
    difficulty: "Alta",
    passRate: "54%",
    color: "#8b5cf6",
    icon: "book-open",
    umaGuideUrl: "https://www.uma.es/etsi-informatica/",
    summary: "Estructuras matemáticas discretas fundamentales para la ciencia computacional. Lógica proposicional, relaciones binarias, combinatoria, teoría de grafos y aritmética modular.",
    topics: [
      "Lógica de proposiciones y de predicados: Métodos de demostración matemática",
      "Teoría de conjuntos, funciones inyectivas/sobreyectivas y cardinalidad",
      "Relaciones binarias: Relaciones de equivalencia y conjuntos cociente",
      "Relaciones de orden parcial, retículos y diagramas de Hasse",
      "Combinatoria: Variaciones, permutaciones, combinaciones y principio del palomar",
      "Teoría de grafos: Conectividad, grafos eulerianos y hamiltonianos, árboles generadores",
      "Grafos planos, coloración de grafos (Teorema de los 4 colores) y congruencias"
    ],
    examTips: "Demostrar propiedades de relaciones (reflexiva, simétrica, transitiva) y problemas de grafos eulerianos con el Teorema de Euler son fijos. Escribe siempre la definición formal antes de operar.",
    wuolahSearchQuery: "Matemática Discreta UMA Grado Software Wuolah",
    wuolahDirectUrl: "https://wuolah.com/apuntes/matematica-discreta?communityId=13891&f_course=1",
    bestWuolahNotes: [
      {
        id: "md-01",
        wuolahUrl: "https://wuolah.com/apuntes/matematica-discreta/apuntes-tema-grafos-rel-binarias-pdf-12678328",
        title: "Apuntes Completos de Grafos, Árboles y Relaciones Binarias",
        rating: 4.9,
        reviewsCount: 37,
        downloads: "10",
        pages: 18,
        type: "Apuntes Completos",
        badge: "Teoría y Práctica",
        uploader: "ana_alfzurbano6",
        isFree: true,
        description: "18 páginas detalladas con diagramas de Hasse, clases de equivalencia, árboles de expansión mínima (Prim/Kruskal) y demostraciones paso a paso de conectividad y planaridad.",
        searchWuolahTerm: "Apuntes tema grafos rel binarias ana_alfzurbano6 matematica discreta"
      },
      {
        id: "md-02",
        wuolahUrl: "https://wuolah.com/apuntes/matematica-discreta/ejercicios-examenes-extraidos-otros-anos-divididos-temas-tema-1-ejercicios-examenes-pdf-11492169",
        title: "Banco de Ejercicios de Exámenes Clasificados por Temas",
        rating: 5.0,
        reviewsCount: 213,
        downloads: "63",
        pages: 14,
        type: "Exámenes por Temas",
        badge: "Más Visto",
        uploader: "Comunidad Wuolah",
        isFree: true,
        description: "Problemas recopilados de más de 8 convocatorias oficiales ordenados por lógica proposicional, recurrencias lineales y combinatoria con soluciones detalladas.",
        searchWuolahTerm: "Ejercicios examenes otros anos divididos temas matematica discreta"
      },
      {
        id: "md-03",
        wuolahUrl: "https://wuolah.com/apuntes/matematica-discreta/apuntes-temas-matematica-discreta-apuntes-tema-2-matematica-discreta-pdf-11559349",
        title: "Apuntes por Temas - Conjuntos, Correspondencias y Relaciones",
        rating: 4.8,
        reviewsCount: 132,
        downloads: "57",
        pages: 10,
        type: "Apuntes por Temas",
        badge: "Top Descargas",
        uploader: "Comunidad Wuolah",
        isFree: true,
        description: "Resumen estructurado de teoría con ejemplos de relaciones de equivalencia, clases congruenciales, particiones de conjuntos y propiedades operacionales.",
        searchWuolahTerm: "Apuntes temas matematica discreta tema 2"
      }
    ]
  },
  {
    id: "105",
    code: "105",
    name: "Organización Empresarial",
    acronym: "OE",
    semester: 1,
    ects: 6,
    type: "Formación Básica",
    category: "gestión",
    difficulty: "Baja",
    passRate: "82%",
    color: "#10b981",
    icon: "briefcase",
    umaGuideUrl: "https://www.uma.es/etsi-informatica/",
    summary: "Concepto de empresa, funciones del empresario, subsistemas organizativos, análisis financiero y criterios de decisión de inversión en empresas de base tecnológica.",
    topics: [
      "La empresa como sistema: Entorno general y específico, responsabilidad social",
      "El empresario y la toma de decisiones: Teorías de la empresa",
      "Subsistema de operaciones y producción: Productividad y costes",
      "Subsistema comercial y marketing: Producto, precio, distribución y promoción",
      "Subsistema financiero: Fuentes de financiación propias y ajenas",
      "Criterios de valoración y selección de inversiones: VAN, TIR y Payback",
      "Estructuras organizativas y diseño de puestos en empresas tecnológicas"
    ],
    examTips: "Los problemas cuantitativos de umbral de rentabilidad (punto muerto) y cálculo de VAN y TIR otorgan muchos puntos fáciles. No olvides comentar el significado económico del resultado.",
    wuolahSearchQuery: "Organización Empresarial Grado Software UMA Wuolah",
    wuolahDirectUrl: "https://wuolah.com/apuntes/organizacion-empresarial?communityId=13891&f_course=1",
    bestWuolahNotes: [
      {
        id: "oe-01",
        wuolahUrl: "https://wuolah.com/apuntes/organizacion-empresarial/tema-1-empresa-empresario-pdf-14041420",
        title: "Apuntes Completos por Temas: Empresa, Estrategia y Subsistemas",
        rating: 4.9,
        reviewsCount: 25,
        downloads: "15",
        pages: 15,
        type: "Apuntes Completos",
        badge: "Diapositivas y Clase",
        uploader: "RubberDucky",
        isFree: true,
        description: "Apuntes actualizados con todo el contenido de las clases y diapositivas oficiales de la UMA: subsistema de producción, marketing mix, subsistema financiero e inversiones.",
        searchWuolahTerm: "Tema 1 empresa empresario RubberDucky organizacion empresarial"
      },
      {
        id: "oe-02",
        wuolahUrl: "https://wuolah.com/apuntes/organizacion-empresarial/parcial-1-empresas-pdf-12688325",
        title: "Examen Parcial 1 Resuelto con Ejercicios Numéricos de VAN y TIR",
        rating: 5.0,
        reviewsCount: 50,
        downloads: "29",
        pages: 7,
        type: "Examen Resuelto",
        badge: "Top Valoración",
        uploader: "Comunidad Wuolah",
        isFree: true,
        description: "Modelo oficial de parcial resuelto con explicaciones de costes fijos, punto muerto, amortizaciones y resolución analítica de proyectos de inversión.",
        searchWuolahTerm: "Parcial 1 empresas organizacion empresarial uma"
      },
      {
        id: "oe-03",
        wuolahUrl: "https://wuolah.com/apuntes/organizacion-empresarial/test-tema-4-4-pdf-11140359",
        title: "Batería de Preguntas Tipo Test de Examen con Respuestas Justificadas",
        rating: 4.8,
        reviewsCount: 19,
        downloads: "9",
        pages: 3,
        type: "Preguntas Test",
        badge: "Práctica Rápida",
        uploader: "panbimbo_",
        isFree: true,
        description: "Compilación de tests de convocatorias anteriores para asegurar la parte tipo test del examen final. Incluye preguntas trampa habituales del profesorado.",
        searchWuolahTerm: "Test tema 4 4 panbimbo_ organizacion empresarial uma"
      }
    ]
  },

  // ==========================================
  // SEGUNDO SEMESTRE
  // ==========================================
  {
    id: "106",
    code: "106",
    name: "Cálculo para la Computación",
    acronym: "CC",
    semester: 2,
    ects: 6,
    type: "Formación Básica",
    category: "math",
    difficulty: "Alta",
    passRate: "51%",
    color: "#6366f1",
    icon: "trending-up",
    umaGuideUrl: "https://www.uma.es/etsi-informatica/",
    summary: "Cálculo diferencial e integral de una y varias variables enfocado a la computación. Sucesiones, series numéricas y de potencias, aproximación de Taylor y optimización numérica.",
    topics: [
      "Números reales y complejos: Topología básica de la recta real",
      "Sucesiones y series numéricas: Criterios de convergencia (D'Alembert, Cauchy, Raabe)",
      "Continuidad y derivabilidad en una variable: Teoremas de Rolle y del Valor Medio",
      "Aproximación polinomial: Polinomios y fórmula del resto de Taylor",
      "Cálculo integral: Teorema Fundamental del Cálculo, integración impropia y numérica",
      "Funciones de varias variables: Límites, derivadas parciales, gradiente y extremos condicionados"
    ],
    examTips: "El estudio de la convergencia de series con parámetros y los problemas de extremos condicionados mediante multiplicadores de Lagrange son imprescindibles en cada convocatoria.",
    wuolahSearchQuery: "Cálculo para la Computación UMA Wuolah Grado Software",
    wuolahDirectUrl: "https://wuolah.com/apuntes/calculo-para-la-computacion?communityId=13891&f_course=1",
    bestWuolahNotes: [
      {
        id: "cc-01",
        wuolahUrl: "https://wuolah.com/apuntes/calculo-para-la-computacion/apuntes-temas-calculo-tema-4-sucesiones-series-ca-lculo-pdf-12324523",
        title: "Apuntes por Temas - Sucesiones, Series Numéricas y Criterios",
        rating: 5.0,
        reviewsCount: 153,
        downloads: "31",
        pages: 14,
        type: "Apuntes Completos",
        badge: "Más Visto",
        uploader: "Comunidad Wuolah",
        isFree: true,
        description: "Desarrollo completo de criterios de convergencia (comparación, cociente, raíz, Leibniz para alternadas) con ejemplos paso a paso y resolución de indeterminaciones.",
        searchWuolahTerm: "Apuntes temas calculo tema 4 sucesiones series"
      },
      {
        id: "cc-02",
        wuolahUrl: "https://wuolah.com/apuntes/calculo-para-la-computacion/apuntes-calculo-tema-4-series-pdf-13257377",
        title: "Apuntes de Cálculo - Series de Potencias y Desarrollos de Taylor",
        rating: 4.9,
        reviewsCount: 69,
        downloads: "50",
        pages: 11,
        type: "Apuntes y Ejercicios",
        badge: "Top Descargas",
        uploader: "Teclister",
        isFree: true,
        description: "50 descargas avalan este documento con cálculo de radios de convergencia, desarrollos en serie de Taylor de funciones elementales y aplicaciones a aproximaciones numéricas.",
        searchWuolahTerm: "Apuntes calculo tema 4 series Teclister uma"
      },
      {
        id: "cc-03",
        wuolahUrl: "https://wuolah.com/apuntes/calculo-para-la-computacion/simulacro-2324-ex-jun-pdf-12307027",
        title: "Simulacro de Examen Oficial Junio Resuelto con Cronómetro",
        rating: 4.9,
        reviewsCount: 67,
        downloads: "11",
        pages: 13,
        type: "Simulacro de Examen",
        badge: "Convocatoria 2024",
        uploader: "ecobuxx",
        isFree: true,
        description: "13 páginas de simulacro de examen oficial cronometrado: derivadas direccionales, hessianos para clasificar puntos críticos e integrales impropias resueltas con detalle.",
        searchWuolahTerm: "Simulacro 2324 ex jun ecobuxx calculo uma"
      }
    ]
  },
  {
    id: "107",
    code: "107",
    name: "Estructuras Algebraicas",
    acronym: "EA",
    semester: 2,
    ects: 6,
    type: "Formación Básica",
    category: "math",
    difficulty: "Muy Alta",
    passRate: "46%",
    color: "#ec4899",
    icon: "hash",
    umaGuideUrl: "https://www.uma.es/etsi-informatica/",
    summary: "Estructuras algebraicas abstractas (grupos, anillos, cuerpos), álgebra lineal, espacios vectoriales, aplicaciones lineales, diagonalización y formas cuadráticas.",
    topics: [
      "Operaciones binarias internas y leyes de composición",
      "Grupos, subgrupos, homomorfismos y Teorema de Lagrange",
      "Anillos y cuerpos: El cuerpo de los números complejos y aritmética polinómica",
      "Espacios y subespacios vectoriales: Sistemas de generadores, base y dimensión",
      "Aplicaciones lineales: Matriz asociada, núcleo, imagen y cambio de base",
      "Diagonalización de matrices: Valores propios, vectores propios y polinomios característicos",
      "Espacio euclídeo: Producto escalar, ortogonalidad y método de Gram-Schmidt"
    ],
    examTips: "Asegúrate de dominar el cálculo de subespacios vectoriales (suma e intersección con la fórmula de Grassmann) y la diagonalización por semejanza y ortogonal. Caen en el 100% de los exámenes.",
    wuolahSearchQuery: "Estructuras Algebraicas para la Computacion UMA Wuolah",
    wuolahDirectUrl: "https://wuolah.com/apuntes/estructuras-algebraicas-para-la-computacion?communityId=13891&f_course=1",
    bestWuolahNotes: [
      {
        id: "ea-01",
        wuolahUrl: "https://wuolah.com/apuntes/estructuras-algebraicas-para-la-computacion/examenes-hechos-algebra-examen-hecho-septiembre-2021-pdf-12275535",
        title: "Recopilación de Exámenes Oficiales Resueltos de Álgebra",
        rating: 5.0,
        reviewsCount: 194,
        downloads: "49",
        pages: 16,
        type: "Exámenes Resueltos",
        badge: "Más Visto",
        uploader: "Comunidad Wuolah",
        isFree: true,
        description: "Casi 200 consultas en Wuolah. Exámenes oficiales desarrollados con cálculo de autovalores, comprobación de multiplicidad algebraica vs geométrica y ortogonalización de Gram-Schmidt.",
        searchWuolahTerm: "Examenes hechos algebra examen hecho septiembre 2021"
      },
      {
        id: "ea-02",
        wuolahUrl: "https://wuolah.com/apuntes/estructuras-algebraicas-para-la-computacion/aprobado-algebra-bloque-2-completo-pdf-12281342",
        title: "Pack Aprobado Garantizado - Álgebra Bloque 2 Completo",
        rating: 4.9,
        reviewsCount: 29,
        downloads: "22",
        pages: 8,
        type: "Apuntes Completos",
        badge: "Top Aprobados",
        uploader: "pinkypink",
        isFree: true,
        description: "Esquema conciso y directo para aprobar el segundo bloque: aplicaciones lineales, matrices de paso, cálculo del núcleo e imagen paso a paso sin rodeos teóricos innecesarios.",
        searchWuolahTerm: "Aprobado algebra bloque 2 completo pinkypink uma"
      },
      {
        id: "ea-03",
        wuolahUrl: "https://wuolah.com/apuntes/estructuras-algebraicas-para-la-computacion/apuntes-t-5-espacios-vectoriales-pdf-12247651",
        title: "Apuntes Tema 5 - Espacios y Subespacios Vectoriales",
        rating: 4.8,
        reviewsCount: 34,
        downloads: "20",
        pages: 6,
        type: "Apuntes por Temas",
        badge: "Muy Valorado",
        uploader: "Genji",
        isFree: true,
        description: "Teoría explicada y ejercicios de rango, cálculo de bases de subespacios vectoriales dados por ecuaciones implícitas y paramétricas, y suma directa.",
        searchWuolahTerm: "Apuntes T5 espacios vectoriales Genji algebra uma"
      }
    ]
  },
  {
    id: "108",
    code: "108",
    name: "Introducción a la Ingeniería del Software",
    acronym: "IIS",
    semester: 2,
    ects: 6,
    type: "Obligatoria",
    category: "software",
    difficulty: "Media",
    passRate: "70%",
    color: "#06b6d4",
    icon: "layers",
    umaGuideUrl: "https://www.uma.es/etsi-informatica/",
    summary: "Ciclo de vida del software, metodologías de desarrollo (cascada, ágiles/Scrum), ingeniería de requisitos, modelado con UML (casos de uso, clases, secuencia) y diseño arquitectónico.",
    topics: [
      "Conceptos fundamentales y crisis del software: Procesos y ciclos de vida",
      "Metodologías ágiles: Valores del Manifiesto Ágil, marco de trabajo Scrum y Kanban",
      "Ingeniería de requisitos: Requisitos funcionales y no funcionales, historias de usuario",
      "Modelado de sistemas con UML: Diagramas de Casos de Uso y especificaciones",
      "Modelado conceptual y estructural: Diagramas de Clases de dominio y relaciones",
      "Modelado del comportamiento: Diagramas de Secuencia, Comunicación y Estados",
      "Introducción a las pruebas del software: Pruebas unitarias con JUnit y calidad"
    ],
    examTips: "El diseño de diagramas de clases y de secuencia para un caso de estudio real representa más del 50% de la nota del examen. No olvides las multiplicidades ni los tipos de relación (composición vs agregación).",
    wuolahSearchQuery: "Introducción a la Ingeniería del Software UMA Wuolah",
    wuolahDirectUrl: "https://wuolah.com/apuntes/ntroduccion-a-la-ingenieria-del-software?communityId=13891&f_course=2",
    bestWuolahNotes: [
      {
        id: "iis-01",
        wuolahUrl: "https://wuolah.com/apuntes/ntroduccion-a-la-ingenieria-del-software/examenes-enunciado-practica-primera-convocatoria-junio-pdf-10548736",
        title: "Recopilación de Exámenes y Enunciados de Prácticas de Convocatorias",
        rating: 5.0,
        reviewsCount: 311,
        downloads: "244",
        pages: 18,
        type: "Exámenes Oficiales",
        badge: "Super Top 244+",
        uploader: "candeladav",
        isFree: true,
        description: "El recurso más descargado de la asignatura en Wuolah (+240 descargas). Enunciados y resoluciones de exámenes de junio y prácticas sobre modelado UML completo.",
        searchWuolahTerm: "Examenes enunciado practica primera convocatoria junio candeladav iis"
      },
      {
        id: "iis-02",
        wuolahUrl: "https://wuolah.com/apuntes/ntroduccion-a-la-ingenieria-del-software/apuntes-bloque-2-introduccion-ingenieria-sofrware-pdf-12057388",
        title: "Apuntes Bloque 2 - Modelado UML de Clases, Casos de Uso y Secuencia",
        rating: 4.9,
        reviewsCount: 157,
        downloads: "40",
        pages: 14,
        type: "Apuntes Completos",
        badge: "Top Valoración",
        uploader: "Genji",
        isFree: true,
        description: "Guía completa de 14 páginas sobre modelado conceptual: reglas de consistencia entre diagramas, identificación de clases de dominio, atributos y dependencias.",
        searchWuolahTerm: "Apuntes bloque 2 introduccion ingenieria software Genji"
      },
      {
        id: "iis-03",
        wuolahUrl: "https://wuolah.com/apuntes/ntroduccion-a-la-ingenieria-del-software/modelado-parcial-2023-resuelto-pdf-8144546",
        title: "Examen Parcial de Modelado UML 2023 Resuelto",
        rating: 4.8,
        reviewsCount: 132,
        downloads: "30",
        pages: 2,
        type: "Parcial Resuelto",
        badge: "Examen Parcial",
        uploader: "macodecena",
        isFree: true,
        description: "Solución completa y comentada del examen parcial de modelado: diagramas de casos de uso y clases con justificación de multiplicidades y atributos de asociación.",
        searchWuolahTerm: "Modelado parcial 2023 resuelto macodecena iis uma"
      }
    ]
  },
  {
    id: "109",
    code: "109",
    name: "Programación Avanzada I",
    acronym: "PA I",
    semester: 2,
    ects: 6,
    type: "Obligatoria",
    category: "software",
    difficulty: "Alta",
    passRate: "59%",
    color: "#14b8a6",
    icon: "cpu",
    umaGuideUrl: "https://www.uma.es/etsi-informatica/",
    summary: "Paradigma de Orientación a Objetos (POO). Encapsulación, herencia, polimorfismo, interfaces, colecciones genéricas, manejo robusto de excepciones y flujos de E/S en Java/C++.",
    topics: [
      "Paradigma de Orientación a Objetos: Clases, objetos, estado y comportamiento",
      "Encapsulamiento, modificadores de acceso y métodos constructores/destructores",
      "Relaciones entre clases: Asociación, agregación, composición y herencia",
      "Polimorfismo, clases abstractas e interfaces",
      "Gestión de errores y robustez: Jerarquía y propagación de excepciones",
      "Colecciones genéricas (List, Set, Map): Iteradores y algoritmos estándar",
      "Flujos de entrada/salida (E/S): Persistencia básica de objetos"
    ],
    examTips: "Es clave dominar el uso correcto de interfaces (Comparable, Comparator) y el polimorfismo dinámico. En el examen práctico, diseña la jerarquía de clases limpiamente antes de programar la lógica.",
    wuolahSearchQuery: "Programación Avanzada Programación Orientada a Objetos UMA Wuolah",
    wuolahDirectUrl: "https://wuolah.com/apuntes/programacion-orientada-a-objetos?communityId=13891&f_course=1",
    bestWuolahNotes: [
      {
        id: "pa-01",
        wuolahUrl: "https://wuolah.com/apuntes/programacion-orientada-a-objetos/controles-anos-anteriores-control-marzo-2023-pdf-11855165",
        title: "Controles de Años Anteriores Resueltos con Código Fuente",
        rating: 5.0,
        reviewsCount: 65,
        downloads: "123",
        pages: 14,
        type: "Controles Resueltos",
        badge: "Más de 120 descargas",
        uploader: "candeladav",
        isFree: true,
        description: "Exámenes completos de controles de años anteriores con enunciados, código fuente depurado y soluciones explicadas de herencia y colecciones.",
        searchWuolahTerm: "Controles anos anteriores control marzo 2023 candeladav poo"
      },
      {
        id: "pa-02",
        wuolahUrl: "https://wuolah.com/apuntes/programacion-orientada-a-objetos/tema-2-herencia-interfaces-pdf-10098481",
        title: "Apuntes Tema 2 - Herencia, Clases Abstractas e Interfaces",
        rating: 4.9,
        reviewsCount: 72,
        downloads: "35",
        pages: 12,
        type: "Apuntes Completos",
        badge: "Muy Recomendado",
        uploader: "candeladav",
        isFree: true,
        description: "12 páginas con diagramas de clases, ejemplos prácticos de polimorfismo dinámico, llamadas a super(), ligadura dinámica y buenas prácticas de diseño orientado a objetos.",
        searchWuolahTerm: "Tema 2 herencia interfaces candeladav programacion avanzada"
      },
      {
        id: "pa-03",
        wuolahUrl: "https://wuolah.com/apuntes/programacion-orientada-a-objetos/apuntes-prog-avanzada-pdf-10576106",
        title: "Apuntes de Programación Avanzada - Colecciones y Excepciones",
        rating: 4.8,
        reviewsCount: 75,
        downloads: "33",
        pages: 4,
        type: "Resumen Rápido",
        badge: "Esquema Clave",
        uploader: "juliaaa22",
        isFree: true,
        description: "Esquemas y ejemplos sintácticos rápidos para dominar el uso de Mapas, Listas, Conjuntos e implementación limpia de bloques try-catch-finally.",
        searchWuolahTerm: "Apuntes prog avanzada juliaaa22 uma"
      }
    ]
  },
  {
    id: "110",
    code: "110",
    name: "Tecnología de Computadores",
    acronym: "TC",
    semester: 2,
    ects: 6,
    type: "Formación Básica",
    category: "hardware",
    difficulty: "Alta",
    passRate: "52%",
    color: "#f97316",
    icon: "server",
    umaGuideUrl: "https://www.uma.es/etsi-informatica/",
    summary: "Sistemas digitales y arquitectura de computadores. Álgebra de Boole, diseño de circuitos combinacionales y secuenciales, biestables, registros, autómata de estados y diseño de CPU elemental (RISC-V).",
    topics: [
      "Representación de la información: Complemento a 2, coma fija y estándar IEEE 754",
      "Álgebra de Boole y simplificación de funciones: Mapas de Karnaugh",
      "Bloques combinacionales estándar: Decodificadores, multiplexores, sumadores y comparadores",
      "Circuitos secuenciales: Biestables (SR, JK, D, T) y diagramas de tiempos",
      "Diseño de registros, contadores sincrónicos y bancos de registros",
      "Diseño de máquinas de estados finitos (FSM): Modelos Mealy y Moore",
      "Introducción a la arquitectura de una CPU simple: Ruta de datos y unidad de control (RISC-V)"
    ],
    examTips: "Los problemas de diseño de autómatas Mealy/Moore a partir de un enunciado y la representación de números en IEEE 754 de precisión simple caen invariablemente.",
    wuolahSearchQuery: "Tecnología de Computadores TC UMA Wuolah",
    wuolahDirectUrl: "https://wuolah.com/apuntes/tecnologia-de-computadores?communityId=13891&f_course=1",
    bestWuolahNotes: [
      {
        id: "tc-01",
        wuolahUrl: "https://wuolah.com/apuntes/tecnologia-de-computadores/apuntes-tema-2-representacion-informacion-pdf-11909840",
        title: "Apuntes Tema 2 - Representación de la Información e IEEE 754",
        rating: 5.0,
        reviewsCount: 94,
        downloads: "23",
        pages: 3,
        type: "Apuntes y Fórmulas",
        badge: "Top Valoración",
        uploader: "Genji",
        isFree: true,
        description: "Explicación directa de la representación en coma flotante IEEE 754 (signo, exponente con sesgo, mantisa), complemento a 2 y rango dinámico con ejercicios resueltos.",
        searchWuolahTerm: "Apuntes tema 2 representacion informacion Genji tc"
      },
      {
        id: "tc-02",
        wuolahUrl: "https://wuolah.com/apuntes/tecnologia-de-computadores/circuitos-risc-v-hechos-sa-29-riscv-saltos-condicionales-zip-12196564",
        title: "Colección de Circuitos y Simulaciones RISC-V Hechos",
        rating: 4.9,
        reviewsCount: 15,
        downloads: "90",
        pages: 8,
        type: "Prácticas de Simulador",
        badge: "90 Descargas",
        uploader: "Comunidad Wuolah",
        isFree: true,
        description: "El material de laboratorio más descargado (90 descargas): circuitos y modelos de ruta de datos RISC-V con saltos condicionales, carga y almacenamiento en memoria.",
        searchWuolahTerm: "Circuitos RISC-V hechos saltos condicionales tc uma"
      },
      {
        id: "tc-03",
        wuolahUrl: "https://wuolah.com/apuntes/tecnologia-de-computadores/examen-tema-4-pdf-10511819",
        title: "Examen Oficial Tema 4 - Circuitos Secuenciales y Biestables",
        rating: 4.8,
        reviewsCount: 30,
        downloads: "15",
        pages: 2,
        type: "Examen Resuelto",
        badge: "Examen Tema 4",
        uploader: "laiadiazg",
        isFree: true,
        description: "Examen resuelto paso a paso sobre análisis y síntesis de circuitos secuenciales sincrónicos con biestables D y JK, tabla de excitación y cronogramas temporales.",
        searchWuolahTerm: "Examen tema 4 laiadiazg tecnologia de computadores uma"
      }
    ]
  }
];

// Consejos clave de supervivencia para 1º año en la UMA ETSI Informática
const WUOLAH_SURVIVAL_TIPS = [
  {
    title: "Filtrado Cruzado Inteligente",
    description: "En 1º de carrera, muchas asignaturas son comunes con el Grado en Ingeniería Informática y Grado en Ingeniería de Computadores de la UMA. Si un apunte en Wuolah para Software tiene pocas descargas, búscalo en la sección de Grado en Ingeniería Informática: ¡los profesores y temarios son idénticos!"
  },
  {
    title: "Prioriza Exámenes y Formularios",
    description: "Los exámenes en la ETSI Informática siguen patrones muy consistentes año tras año. Empezar a estudiar resolviendo exámenes de convocatorias pasadas desde la mitad del cuatrimestre es la técnica más efectiva para aprobar a la primera."
  },
  {
    title: "Verifica las Estrellas y Comentarios",
    description: "En Wuolah, fíjate siempre en documentos con más de 4.8 estrellas y comentarios recientes. Los apuntes que llevan la etiqueta 'Matrícula de Honor' o que tienen esquemas a color suelen ser los más ordenados y fiables."
  },
  {
    title: "Prácticas de Laboratorio (SageMath, C++, C)",
    description: "No descuides las prácticas de laboratorio en asignaturas como Matemática Discreta o Introducción a la Programación. Aprobar el laboratorio suele ser condición indispensable para superar la asignatura en la convocatoria ordinaria."
  }
];

if (typeof window !== 'undefined') {
  window.SUBJECTS_DATA = SUBJECTS_DATA;
  window.WUOLAH_SURVIVAL_TIPS = WUOLAH_SURVIVAL_TIPS;
}
