/**
 * Base de datos oficial de Asignaturas de 1º de Ingeniería del Software (Plan 2023)
 * Escuela Técnica Superior de Ingeniería Informática - Universidad de Málaga (UMA)
 * Incluye recursos y apuntes de Wuolah mejor valorados, enlaces y guías.
 */

const SUBJECTS_DATA = [
  // ==========================================
  // PRIMER SEMESTRE
  // ==========================================
  {
    id: "101",
    code: "101",
    name: "Fundamentos de Electrónica",
    acronym: "FEl",
    semester: 1,
    ects: 6,
    type: "Formación Básica",
    category: "hardware",
    difficulty: "Alta",
    passRate: "58%",
    color: "#f59e0b",
    icon: "zap",
    umaGuideUrl: "https://www.uma.es/etsi-informatica/",
    summary: "Estudio de las señales eléctricas, física de semiconductores, componentes analógicos y diseño básico de puertas lógicas electrónicas que sustentan los computadores.",
    topics: [
      "Señales analógicas y digitales, análisis de circuitos en régimen permanente",
      "Dispositivos semiconductores: Diodos de unión PN, rectificadores, diodos Zener",
      "Transistores de Unión Bipolar (BJT): Polarización, recta de carga y amplificación",
      "Transistores de Efecto de Campo (MOSFET): Comportamiento como interruptor y lógica CMOS",
      "Amplificadores Operacionales (AmpOp): Configuraciones inversora, no inversora, sumador y comparador",
      "Familias lógicas y circuitos electrónicos de conmutación"
    ],
    examTips: "Los ejercicios con amplificadores operacionales y el cálculo del punto de operación (Q) en BJT/MOSFET caen siempre en los parciales. Asegúrate de verificar siempre si el transistor está en zona activa o saturación.",
    wuolahSearchQuery: "Fundamentos de Electrónica UMA Grado Informatica Software",
    wuolahDirectUrl: "https://www.wuolah.com/uma/ingenieria-del-software",
    bestWuolahNotes: [
      {
        id: "fel-01",
        pdfPath: "pdfs/fel-01.pdf",
        isAvailable: true,
        fileSize: "2.9 KB",
        directVerified: true,
        title: "Apuntes Completos de Teoría y Problemas Paso a Paso (Matrícula de Honor)",
        rating: 4.9,
        reviewsCount: 142,
        downloads: "1.6k",
        pages: 94,
        type: "Apuntes Completos",
        badge: "Top Valoración",
        uploader: "Doc_Electromaster",
        description: "Esquemas a todo color de circuitos, modelos en pequeña señal de BJT y MOS explicados con detalle, y metodología sistemática para resolver cualquier problema de amplificadores operacionales.",
        searchWuolahTerm: "Fundamentos de Electronica UMA apuntes completos teoria problemas"
      },
      {
        id: "fel-02",
        pdfPath: "pdfs/fel-02.pdf",
        isAvailable: true,
        fileSize: "2.8 KB",
        directVerified: true,
        title: "Colección de Exámenes Resueltos Parciales y Convocatorias (2020-2024)",
        rating: 5.0,
        reviewsCount: 189,
        downloads: "2.1k",
        pages: 112,
        type: "Exámenes Resueltos",
        badge: "Imprescindible Examen",
        uploader: "InforUMA_Pro",
        description: "Exámenes resueltos minuciosamente con comprobaciones de saturación en transistores, diagramas de Bode de AmpOp y notas al margen sobre errores comunes que restan puntos.",
        searchWuolahTerm: "Fundamentos Electronica UMA examenes resueltos parciales"
      },
      {
        id: "fel-03",
        pdfPath: "pdfs/fel-03.pdf",
        isAvailable: true,
        fileSize: "2.7 KB",
        directVerified: true,
        title: "Formulario Oficial Ampliado con Resumen de Configuraciones AmpOp y Diodos",
        rating: 4.8,
        reviewsCount: 78,
        downloads: "950",
        pages: 8,
        type: "Formulario",
        badge: "Chuleta Rápida",
        uploader: "Apolo_Notes",
        description: "Resumen ultra compacto con todas las ecuaciones de Shockley, fórmulas de ganancia en AmpOp, curvas características y tablas de polarización para repasar antes de entrar al aula.",
        searchWuolahTerm: "Formulario Fundamentos de Electronica UMA"
      }
    ]
  },
  {
    id: "102",
    code: "102",
    name: "Fundamentos Físicos de la Informática",
    acronym: "FFI",
    semester: 1,
    ects: 6,
    type: "Formación Básica",
    category: "hardware",
    difficulty: "Muy Alta",
    passRate: "48%",
    color: "#ef4444",
    icon: "compass",
    umaGuideUrl: "https://www.uma.es/etsi-informatica/",
    summary: "Comprensión de los principios del electromagnetismo, electrostática y leyes de circuitos que rigen el funcionamiento del hardware y almacenamiento digital.",
    topics: [
      "Electrostática en el vacío: Ley de Coulomb, campo electrostático y potencial",
      "Teorema de Gauss y cálculo de campos con simetría cilíndrica, esférica y plana",
      "Conductores en equilibrio electrostático, capacidad y dieléctricos",
      "Corriente eléctrica continua: Resistencia, Ley de Ohm y Leyes de Kirchhoff",
      "Campo magnético y fuerzas magnéticas: Ley de Lorentz y Ley de Biot-Savart",
      "Ley de Ampère, inducción electromagnética (Ley de Faraday-Lenz) e inductancia"
    ],
    examTips: "Es una de las asignaturas 'filtro' del 1º año. Dedica especial atención a calcular integrales de Gauss con diferentes densidades de carga volumétrica/superficial y a plantear mallas con generadores dependientes.",
    wuolahSearchQuery: "Fundamentos Físicos de la Informática UMA Wuolah",
    wuolahDirectUrl: "https://www.wuolah.com/uma/ingenieria-del-software",
    bestWuolahNotes: [
      {
        id: "ffi-01",
        pdfPath: "pdfs/ffi-01.pdf",
        isAvailable: true,
        fileSize: "3 KB",
        directVerified: true,
        title: "Super-Resumen FFI: Teoría Simplificada y Ejercicios Tipo Examen Comentados",
        rating: 4.9,
        reviewsCount: 265,
        downloads: "2.8k",
        pages: 88,
        type: "Apuntes Completos",
        badge: "El Mejor Explicado",
        uploader: "FisicoInformaticaUMA",
        description: "Explica la teoría con intuición física sin perder rigor matemático. Resuelve paso a paso los ejercicios de campos que más repiten los profesores de la ETSI Informática.",
        searchWuolahTerm: "Fundamentos Fisicos de la Informatica UMA apuntes completos"
      },
      {
        id: "ffi-02",
        pdfPath: "pdfs/ffi-02.pdf",
        isAvailable: true,
        fileSize: "2.8 KB",
        directVerified: true,
        title: "Recopilatorio de Parciales y Finales Resueltos por Temas (Ordinaria y Extraordinaria)",
        rating: 5.0,
        reviewsCount: 310,
        downloads: "3.4k",
        pages: 145,
        type: "Exámenes Resueltos",
        badge: "Top Descargas",
        uploader: "Pablo_IngSoftware",
        description: "Considerado el archivo 'salva-vidas' de FFI en la UMA. Contiene más de 40 problemas de examen de cursos recientes desarrollados a mano con letra impecable y explicaciones claras.",
        searchWuolahTerm: "Fundamentos Fisicos Informatica UMA examenes resueltos"
      },
      {
        id: "ffi-03",
        pdfPath: "pdfs/ffi-03.pdf",
        isAvailable: true,
        fileSize: "2.7 KB",
        directVerified: true,
        title: "Chuletario / Formulario Completo de Física con Diagramas de Superficies Gaussianas",
        rating: 4.8,
        reviewsCount: 115,
        downloads: "1.2k",
        pages: 6,
        type: "Formulario",
        badge: "Chuleta Rápida",
        uploader: "Kike_UMA",
        description: "Todas las fórmulas vectoriales, constantes físicas universales, tablas de momentos de inercia y esquemas de orientación para el producto vectorial y ley de la mano derecha.",
        searchWuolahTerm: "Formulario Fundamentos Fisicos UMA"
      }
    ]
  },
  {
    id: "103",
    code: "103",
    name: "Introducción a la Programación",
    acronym: "IP",
    semester: 1,
    ects: 6,
    type: "Formación Básica",
    category: "programming",
    difficulty: "Media",
    passRate: "68%",
    color: "#06b6d4",
    icon: "code",
    umaGuideUrl: "https://www.uma.es/etsi-informatica/",
    summary: "Base fundamental de la algoritmia y programación estructurada en C/C++. Enfoque en tipos de datos, estructuras de control, modularidad, punteros básicos y gestión de ficheros.",
    topics: [
      "Metodología de la programación estructurada y resolución sistemática de problemas",
      "Tipos de datos básicos, operadores, expresiones y conversiones de tipo",
      "Estructuras de control de flujo: Selección (if-else, switch) y repetición (while, for, do-while)",
      "Diseño modular: Funciones, paso de parámetros por valor y por referencia",
      "Estructuras de datos homogéneas (vectores unidimensionales y matrices)",
      "Estructuras de datos heterogéneas (registros/structs) y cadenas de caracteres",
      "Algoritmos de búsqueda secuencial y binaria; algoritmos de ordenación clásicos",
      "Tratamiento de flujos de entrada/salida y ficheros de texto y binarios"
    ],
    examTips: "Los exámenes prácticos de ordenador penalizan mucho los bucles infinitos, los fallos de acceso fuera de rango en arrays y no cerrar ficheros abiertos. Practica escribir código limpio y bien indentado.",
    wuolahSearchQuery: "Introducción a la Programación UMA Informática Wuolah C++",
    wuolahDirectUrl: "https://www.wuolah.com/uma/ingenieria-del-software",
    bestWuolahNotes: [
      {
        id: "ip-01",
        pdfPath: "pdfs/ip-01.pdf",
        isAvailable: true,
        fileSize: "3.1 KB",
        directVerified: true,
        title: "Guía Definitiva de Algoritmia y Código C++ Explicado Línea a Línea",
        rating: 5.0,
        reviewsCount: 420,
        downloads: "3.9k",
        pages: 130,
        type: "Apuntes Completos",
        badge: "Imprescindible",
        uploader: "CodeMaster_Malaga",
        description: "Desde el 'Hello World' hasta algoritmos complejos de matrices y ficheros binarios. Incluye diagramas de memoria con la pila de llamadas (call stack) para entender el paso por referencia.",
        searchWuolahTerm: "Introduccion a la Programacion C++ UMA apuntes completos"
      },
      {
        id: "ip-02",
        pdfPath: "pdfs/ip-02.pdf",
        isAvailable: true,
        fileSize: "2.8 KB",
        directVerified: true,
        title: "Pack de Prácticas de Laboratorio y Exámenes en Ordenador Resueltos",
        rating: 4.9,
        reviewsCount: 230,
        downloads: "2.7k",
        pages: 98,
        type: "Prácticas & Exámenes",
        badge: "Aprobado Garantizado",
        uploader: "Sara_SW_Eng",
        description: "Contiene todos los enunciados de laboratorio de los últimos 3 años resueltos con código fuente comentado, explicaciones de las estructuras de datos usadas y casos de prueba edge case.",
        searchWuolahTerm: "Introduccion Programacion UMA practicas examenes laboratorio"
      },
      {
        id: "ip-03",
        pdfPath: "pdfs/ip-03.pdf",
        isAvailable: true,
        fileSize: "2.6 KB",
        directVerified: true,
        title: "Chuleta Sintáctica y Algoritmos Canónicos en C++ (Ordenación, Búsqueda y Ficheros)",
        rating: 4.9,
        reviewsCount: 160,
        downloads: "1.8k",
        pages: 12,
        type: "Formulario",
        badge: "Guía Rápida",
        uploader: "DevUMA",
        description: "Sintaxis precisa de structs, paso de matrices a funciones, plantillas para leer/escribir ficheros y los códigos de ordenación por burbuja, inserción y selección.",
        searchWuolahTerm: "Chuleta Introduccion Programacion C++ UMA"
      }
    ]
  },
  {
    id: "104",
    code: "104",
    name: "Matemática Discreta",
    acronym: "MD",
    semester: 1,
    ects: 6,
    type: "Formación Básica",
    category: "math",
    difficulty: "Alta",
    passRate: "60%",
    color: "#8b5cf6",
    icon: "git-commit",
    umaGuideUrl: "https://www.uma.es/etsi-informatica/",
    summary: "Herramientas matemáticas esenciales para el software: lógica formal, inducción, combinatoria, teoría de grafos, relaciones y aritmética modular aplicada a la computación.",
    topics: [
      "Lógica proposicional y de predicados: Tablas de verdad, formas normales y deducción natural",
      "Teoría de conjuntos, relaciones binarias (equivalencia y orden) y funciones",
      "Principio de inducción matemática y relaciones de recurrencia",
      "Combinatoria: Variaciones, permutaciones, combinaciones y principio del palomar",
      "Teoría de grafos: Caminos, ciclos de Euler y Hamilton, árboles generadores mínimos (Kruskal, Prim)",
      "Algoritmos de caminos mínimos (Dijkstra, Bellman-Ford) y coloreado de grafos",
      "Aritmética modular: Algoritmo de Euclides extendido, congruencias y Teorema Chino del Resto",
      "Prácticas de laboratorio con el software matemático SageMath"
    ],
    examTips: "La deducción natural y los problemas de congruencias/inversas modulares son preguntas fijas. En el examen de laboratorio con SageMath es clave dominar las funciones de grafos y aritmética.",
    wuolahSearchQuery: "Matemática Discreta UMA Wuolah SageMath",
    wuolahDirectUrl: "https://www.wuolah.com/uma/ingenieria-del-software",
    bestWuolahNotes: [
      {
        id: "md-01",
        pdfPath: "pdfs/md-01.pdf",
        isAvailable: true,
        fileSize: "3.1 KB",
        directVerified: true,
        title: "Apuntes Clarísimos Matemática Discreta + Manual Completo de SageMath",
        rating: 5.0,
        reviewsCount: 290,
        downloads: "3.1k",
        pages: 110,
        type: "Apuntes Completos",
        badge: "Top Valoración",
        uploader: "DiscreteGenius",
        description: "Apuntes con explicaciones intuitivas y sin tecnicismos excesivos. Incluye un anexo imprescindible con todos los comandos de SageMath comentados para el examen de prácticas.",
        searchWuolahTerm: "Matematica Discreta UMA apuntes completos sagemath"
      },
      {
        id: "md-02",
        pdfPath: "pdfs/md-02.pdf",
        isAvailable: true,
        fileSize: "2.6 KB",
        directVerified: true,
        title: "Exámenes Resueltos y Relaciones de Problemas Comentadas (Convocatorias Completas)",
        rating: 4.9,
        reviewsCount: 198,
        downloads: "2.4k",
        pages: 85,
        type: "Exámenes Resueltos",
        badge: "Muy Recomendado",
        uploader: "Carlos_ETSII",
        description: "Ejercicios de grafos, árboles y deducción natural con el árbol de inferencia dibujado paso a paso indicando cada regla aplicada (introducción y eliminación de conectores).",
        searchWuolahTerm: "Matematica Discreta UMA examenes resueltos problemas"
      },
      {
        id: "md-03",
        pdfPath: "pdfs/md-03.pdf",
        isAvailable: true,
        fileSize: "2.6 KB",
        directVerified: true,
        title: "Formulario de Deducción Natural, Reglas de Inferencia y Métodos de Conteo",
        rating: 4.8,
        reviewsCount: 95,
        downloads: "1.5k",
        pages: 7,
        type: "Formulario",
        badge: "Chuleta Rápida",
        uploader: "MathKnight",
        description: "Tabla de reglas de equivalencia lógica, reglas de inferencia para deducción natural, fórmulas de combinatoria con y sin repetición, y propiedades de grafos.",
        searchWuolahTerm: "Formulario Matematica Discreta UMA"
      }
    ]
  },
  {
    id: "105",
    code: "105",
    name: "Organización Empresarial",
    acronym: "OE",
    semester: 1,
    ects: 6,
    type: "Formación Básica",
    category: "business",
    difficulty: "Baja",
    passRate: "82%",
    color: "#10b981",
    icon: "briefcase",
    umaGuideUrl: "https://www.uma.es/etsi-informatica/",
    summary: "Introducción a la estructura económica de la empresa, modelos de negocio digitales, dirección estratégica, contabilidad básica y análisis financiero para ingenieros.",
    topics: [
      "La empresa y el entorno empresarial en el sector de las Tecnologías de la Información",
      "Formas jurídicas de empresa (Sociedad Anónima, Limitada, Autónomos, Startups)",
      "Dirección estratégica: Análisis DAFO, PESTEL, 5 Fuerzas de Porter y cadena de valor",
      "Modelos de negocio tecnológicos: SaaS, Marketplace, Freemium y Software Libre",
      "Gestión de la producción, cadena de suministro y aseguramiento de la calidad",
      "Contabilidad general: Balance de situación patrimonial y Cuenta de Pérdidas y Ganancias",
      "Análisis económico-financiero: Fondo de maniobra, ratios de liquidez, solvencia y rentabilidad",
      "Evaluación de proyectos de inversión: VAN (Valor Actual Neto) y TIR (Tasa Interna de Retorno)"
    ],
    examTips: "Asignatura muy asequible para subir media del expediente. En los exámenes tipo test vigila las respuestas trampa sobre definiciones conceptuales y practica bien los cálculos de VAN, TIR y balance.",
    wuolahSearchQuery: "Organización Empresarial UMA Wuolah Informática",
    wuolahDirectUrl: "https://www.wuolah.com/uma/ingenieria-del-software",
    bestWuolahNotes: [
      {
        id: "oe-01",
        pdfPath: "pdfs/oe-01.pdf",
        isAvailable: true,
        fileSize: "3 KB",
        directVerified: true,
        title: "Resumen Esquematizado para Sobresaliente de Todo el Temario de OE",
        rating: 4.9,
        reviewsCount: 180,
        downloads: "2.2k",
        pages: 62,
        type: "Apuntes Completos",
        badge: "Fácil Estudio",
        uploader: "BizUMA_Star",
        description: "Resumen estructurado con esquemas conceptuales, tablas comparativas de formas societarias y definiciones clave subrayadas. Ideal para memorizar rápido.",
        searchWuolahTerm: "Organizacion Empresarial UMA resumen apuntes"
      },
      {
        id: "oe-02",
        pdfPath: "pdfs/oe-02.pdf",
        isAvailable: true,
        fileSize: "2.7 KB",
        directVerified: true,
        title: "Banco de Preguntas Tipo Test de Exámenes Anteriores con Justificación Razonada",
        rating: 5.0,
        reviewsCount: 240,
        downloads: "2.9k",
        pages: 74,
        type: "Exámenes Resueltos",
        badge: "Top Acierto Test",
        uploader: "TestMaker_UMA",
        description: "Más de 350 preguntas de test reales de convocatorias pasadas con la respuesta correcta marcada y la explicación de por qué las otras opciones son falsas.",
        searchWuolahTerm: "Organizacion Empresarial UMA preguntas test examenes"
      },
      {
        id: "oe-03",
        pdfPath: "pdfs/oe-03.pdf",
        isAvailable: true,
        fileSize: "2.6 KB",
        directVerified: true,
        title: "Plantillas y Problemas Resueltos de Balance, Ratios Financieros y VAN/TIR",
        rating: 4.8,
        reviewsCount: 88,
        downloads: "1.3k",
        pages: 20,
        type: "Problemas Resueltos",
        badge: "Práctico",
        uploader: "EcoCoder",
        description: "Explicación directa de cómo cuadrar el balance activo = pasivo + patrimonio neto, fórmulas de ratios explicadas con ejemplos numéricos y cálculo de rentabilidades.",
        searchWuolahTerm: "Organizacion Empresarial UMA problemas balance ratios"
      }
    ]
  },

  // ==========================================
  // SEGUNDO SEMESTRE
  // ==========================================
  {
    id: "106",
    code: "106",
    name: "Cálculo para la Computación",
    acronym: "CC",
    semester: 2,
    ects: 6,
    type: "Formación Básica",
    category: "math",
    difficulty: "Alta",
    passRate: "54%",
    color: "#ec4899",
    icon: "activity",
    umaGuideUrl: "https://www.uma.es/etsi-informatica/",
    summary: "Cálculo diferencial e integral orientado al análisis de algoritmos, aproximación numérica, series y optimización de funciones multivariables.",
    topics: [
      "El cuerpo de los números reales y complejos; topología elemental",
      "Sucesiones de números reales: Límites y criterios de convergencia",
      "Series numéricas: Criterios de comparación, D'Alembert, Cauchy, Leibniz y series de potencias",
      "Continuidad y derivabilidad en una variable: Teoremas de Rolle y del Valor Medio",
      "Polinomio de Taylor: Desarrollo local, resto de Lagrange y estimación de error computacional",
      "Cálculo integral: Integral de Riemann, Teorema Fundamental del Cálculo y métodos de integración",
      "Integrales impropias y criterios de convergencia",
      "Introducción a las funciones de varias variables, derivadas parciales, gradiente y extremos"
    ],
    examTips: "Los problemas de convergencia de series con parámetros y los desarrollos de Taylor para calcular límites indeterminados son clásicos ineludibles en los exámenes. Repasa a fondo la integración por partes e integrales racionales.",
    wuolahSearchQuery: "Cálculo para la Computación UMA Wuolah Informática",
    wuolahDirectUrl: "https://www.wuolah.com/uma/ingenieria-del-software",
    bestWuolahNotes: [
      {
        id: "cc-01",
        pdfPath: "pdfs/cc-01.pdf",
        isAvailable: true,
        fileSize: "3.1 KB",
        directVerified: true,
        title: "Apuntes Completos Cálculo para la Computación con Demostraciones y Ejemplos",
        rating: 4.9,
        reviewsCount: 220,
        downloads: "2.7k",
        pages: 118,
        type: "Apuntes Completos",
        badge: "Muy Detallado",
        uploader: "CalculusMaster_UMA",
        description: "Desarrollo paso a paso de cada teorema con ejemplos intuitivos de aplicación algorítmica. Incluye resolución detallada de límites por Taylor y cálculo de radios de convergencia.",
        searchWuolahTerm: "Calculo para la Computacion UMA apuntes completos"
      },
      {
        id: "cc-02",
        pdfPath: "pdfs/cc-02.pdf",
        isAvailable: true,
        fileSize: "2.7 KB",
        directVerified: true,
        title: "Colección de Exámenes Resueltos Parciales y Finales (Ordinaria y Extraordinaria)",
        rating: 5.0,
        reviewsCount: 275,
        downloads: "3.2k",
        pages: 132,
        type: "Exámenes Resueltos",
        badge: "Top Descargas",
        uploader: "Alex_UMA_Math",
        description: "Exámenes oficiales redactados con máximo detalle matemático, indicando en cada paso el teorema o criterio aplicado (D'Alembert, Raabe, comparación asintótica, etc.).",
        searchWuolahTerm: "Calculo Computacion UMA examenes resueltos"
      },
      {
        id: "cc-03",
        pdfPath: "pdfs/cc-03.pdf",
        isAvailable: true,
        fileSize: "2.7 KB",
        directVerified: true,
        title: "Formulario Esencial: Desarrollos de Taylor Frecuentes, Criterios de Series y Tabla de Integrales",
        rating: 4.9,
        reviewsCount: 140,
        downloads: "1.9k",
        pages: 5,
        type: "Formulario",
        badge: "Chuleta Rápida",
        uploader: "FormulaKing",
        description: "Los desarrollos de Taylor de las funciones elementales centrados en cero (Maclaurin), tabla completa de criterios de convergencia y fórmulas de integración inmediata.",
        searchWuolahTerm: "Formulario Calculo Computacion UMA Taylor Series"
      }
    ]
  },
  {
    id: "107",
    code: "107",
    name: "Estructuras Algebraicas",
    acronym: "EA",
    semester: 2,
    ects: 6,
    type: "Formación Básica",
    category: "math",
    difficulty: "Muy Alta",
    passRate: "50%",
    color: "#6366f1",
    icon: "layers",
    umaGuideUrl: "https://www.uma.es/etsi-informatica/",
    summary: "Álgebra lineal avanzada y estructuras algebraicas fundamentales (espacios vectoriales, diagonalización, grupos, anillos y cuerpos) aplicadas a la criptografía y seguridad.",
    topics: [
      "Espacios vectoriales y subespacios: Dependencia lineal, bases, dimensión y ecuaciones",
      "Aplicaciones lineales: Matriz asociada, núcleo, imagen y cambio de base",
      "Diagonalización de endomorfismos: Polinomio característico, autovalores y autovectores",
      "Espacio vectorial euclídeo: Producto escalar, norma, ortogonalidad y proceso de Gram-Schmidt",
      "Estructuras algebraicas básicas: Grupos, subgrupos, homomorfismos y Teorema de Lagrange",
      "Anillos y cuerpos: Ideales, dominios de integridad y cuerpos finitos de Galois (GF(p^n))",
      "Aplicación a la codificación detectora/correctora de errores y criptografía de clave pública"
    ],
    examTips: "El cambio de base en aplicaciones lineales y la diagonalización ortogonal son los ejercicios con mayor peso en el examen. Practica hacer cuentas con matrices deprisa y sin equivocarte de signo.",
    wuolahSearchQuery: "Estructuras Algebraicas UMA Informática Wuolah Álgebra",
    wuolahDirectUrl: "https://www.wuolah.com/uma/ingenieria-del-software",
    bestWuolahNotes: [
      {
        id: "ea-01",
        pdfPath: "pdfs/ea-01.pdf",
        isAvailable: true,
        fileSize: "3.1 KB",
        directVerified: true,
        title: "Apuntes Completos de Estructuras Algebraicas para la Computación (Con Gráficos)",
        rating: 5.0,
        reviewsCount: 210,
        downloads: "2.5k",
        pages: 104,
        type: "Apuntes Completos",
        badge: "El Mejor Explicado",
        uploader: "AlgebraPro_UMA",
        description: "Contiene la teoría de álgebra lineal explicada de forma visual y con demostraciones claras, además de una guía especial sobre grupos y cuerpos finitos para entender criptografía.",
        searchWuolahTerm: "Estructuras Algebraicas UMA apuntes completos algebra"
      },
      {
        id: "ea-02",
        pdfPath: "pdfs/ea-02.pdf",
        isAvailable: true,
        fileSize: "2.7 KB",
        directVerified: true,
        title: "Exámenes Resueltos Parciales y Convocatorias Oficiales Completas",
        rating: 4.9,
        reviewsCount: 235,
        downloads: "2.8k",
        pages: 120,
        type: "Exámenes Resueltos",
        badge: "Imprescindible Examen",
        uploader: "Dani_SoftwareETSII",
        description: "Solucionario detallado de problemas de examen: cálculo de matrices asociadas a endomorfismos, subespacios ortogonales y ejercicios de cuerpos finitos resueltos paso a paso.",
        searchWuolahTerm: "Estructuras Algebraicas UMA examenes resueltos parciales"
      },
      {
        id: "ea-03",
        pdfPath: "pdfs/ea-03.pdf",
        isAvailable: true,
        fileSize: "2.7 KB",
        directVerified: true,
        title: "Formulario y Resumen Algorítmico: Pasos de Diagonalización, Gram-Schmidt y Grupos",
        rating: 4.8,
        reviewsCount: 85,
        downloads: "1.4k",
        pages: 8,
        type: "Formulario",
        badge: "Chuleta Rápida",
        uploader: "QuickMatrix",
        description: "Guía 'receta de cocina' con los pasos exactos para diagonalizar matrices, ortogonalizar bases por Gram-Schmidt y propiedades de órdenes de elementos en grupos finitos.",
        searchWuolahTerm: "Formulario Estructuras Algebraicas UMA"
      }
    ]
  },
  {
    id: "108",
    code: "108",
    name: "Introducción a la Ingeniería del Software",
    acronym: "IIS",
    semester: 2,
    ects: 6,
    type: "Obligatoria",
    category: "programming",
    difficulty: "Media",
    passRate: "76%",
    color: "#3b82f6",
    icon: "trello",
    umaGuideUrl: "https://www.uma.es/etsi-informatica/",
    summary: "Asignatura medular del grado: ingeniería de requisitos, ciclo de vida del software, metodologías ágiles (Scrum, Kanban), modelado con UML y diseño orientado a objetos.",
    topics: [
      "Conceptos fundamentales y evolución de la Ingeniería del Software; crisis del software",
      "Ciclos de vida del software: Modelos tradicionales (cascada, espiral) vs metodologías ágiles",
      "Metodologías ágiles: Manifiesto Ágil, roles, ceremonias y artefactos de Scrum, flujo Kanban",
      "Ingeniería de requisitos: Requisitos funcionales y no funcionales, técnicas de elicitación y especificación",
      "Modelado de requisitos mediante Casos de Uso e Historias de Usuario (con criterios INVEST y de aceptación)",
      "Modelado conceptual y diseño estructural con Diagramas de Clases y Paquetes UML",
      "Modelado del comportamiento dinámico con Diagramas de Secuencia y de Estados UML",
      "Principios fundamentales de diseño software: Modularidad, Cohesión, Acoplamiento y principios SOLID",
      "Gestión de versiones con Git/GitHub y conceptos de integración continua (CI/CD)"
    ],
    examTips: "Los profesores son muy rigurosos con la notación UML formal. Aprende a distinguir con total precisión entre agregación (rombo blanco) y composición (rombo negro), y vigila las multiplicidades y flechas en diagramas de secuencia.",
    wuolahSearchQuery: "Introducción a la Ingeniería del Software UMA Wuolah UML",
    wuolahDirectUrl: "https://www.wuolah.com/uma/ingenieria-del-software",
    bestWuolahNotes: [
      {
        id: "iis-01",
        pdfPath: "pdfs/iis-01.pdf",
        isAvailable: true,
        fileSize: "3.1 KB",
        directVerified: true,
        title: "Apuntes Completos IIS: De Metodologías Ágiles al Modelado Riguroso en UML",
        rating: 5.0,
        reviewsCount: 310,
        downloads: "2.6k",
        pages: 96,
        type: "Apuntes Completos",
        badge: "Recomendado 100%",
        uploader: "SoftwareArchitect_UMA",
        description: "Contiene todo el temario explicado con claridad pedagógica, ejemplos reales de especificación de requisitos y decenas de diagramas de clases y secuencias explicados elemento a elemento.",
        searchWuolahTerm: "Introduccion a la Ingenieria del Software UMA apuntes UML"
      },
      {
        id: "iis-02",
        pdfPath: "pdfs/iis-02.pdf",
        isAvailable: true,
        fileSize: "2.8 KB",
        directVerified: true,
        title: "Colección de Casos Prácticos de Examen y Enunciados de Modelado Resueltos",
        rating: 4.9,
        reviewsCount: 195,
        downloads: "2.1k",
        pages: 82,
        type: "Casos Prácticos & Exámenes",
        badge: "Top Prácticas",
        uploader: "Elena_DevEng",
        description: "Supuestos reales de proyectos software (ej. sistema de reservas, e-commerce, gestión hospitalaria) modelados paso a paso: casos de uso, diagrama de clases de diseño y diagramas de secuencia.",
        searchWuolahTerm: "Introduccion Ingenieria Software UMA casos practicos examenes"
      },
      {
        id: "iis-03",
        pdfPath: "pdfs/iis-03.pdf",
        isAvailable: true,
        fileSize: "2.7 KB",
        directVerified: true,
        title: "Guía / Chuleta Rápida: Notación UML 2.5 + Resumen Scrum + Principios SOLID",
        rating: 4.9,
        reviewsCount: 155,
        downloads: "1.7k",
        pages: 10,
        type: "Formulario",
        badge: "Chuleta Rápida",
        uploader: "AgileKing",
        description: "Toda la sintaxis visual de UML en una tabla resumen: relaciones (herencia, realización, asociación, dependencia), visibilidad (+, -, #, ~), artefactos Scrum y principios SOLID.",
        searchWuolahTerm: "Chuleta UML sintaxis Ingenieria del Software UMA"
      }
    ]
  },
  {
    id: "109",
    code: "109",
    name: "Programación Avanzada I",
    acronym: "PA I",
    semester: 2,
    ects: 6,
    type: "Formación Básica",
    category: "programming",
    difficulty: "Alta",
    passRate: "62%",
    color: "#0284c7",
    icon: "terminal",
    umaGuideUrl: "https://www.uma.es/etsi-informatica/",
    summary: "Profundización en el paradigma orientado a objetos, diseño modular en C++/Java, gestión dinámica de memoria en profundidad y desarrollo de Tipos Abstractos de Datos (TADs).",
    topics: [
      "El paradigma de la Programación Orientada a Objetos: Clases, objetos, estado y comportamiento",
      "Encapsulamiento, ocultamiento de información y métodos de acceso (getters/setters)",
      "Ciclo de vida de los objetos: Constructores por defecto, por parámetros y por copia; Destructores",
      "Gestión dinámica de memoria avanzada: Operadores new/delete, punteros inteligentes (smart pointers) y fuga de memoria",
      "Sobrecarga de operadores (aritméticos, asignación profunda =, flujo << y >>)",
      "Relación de herencia simple y jerárquica: Clases base y derivadas; Modificador protected",
      "Polimorfismo en tiempo de ejecución: Métodos virtuales, tablas de métodos virtuales (vtable) y destructores virtuales",
      "Clases abstractas, interfaces y polimorfismo paramétrico (plantillas / templates de clases)",
      "Tipos Abstractos de Datos (TADs) dinámicos: Implementación de listas enlazadas, pilas y colas",
      "Gestión de excepciones (try, catch, throw) y buenas prácticas de codificación"
    ],
    examTips: "El punto crítico de la asignatura es la 'Regla de los Tres/Cinco' (destructor, constructor de copia y operador de asignación). Si olvidas un delete o liberas memoria dos veces, el test automatizado te pondrá un 0 en ese ejercicio.",
    wuolahSearchQuery: "Programación Avanzada I UMA Wuolah C++ POO",
    wuolahDirectUrl: "https://www.wuolah.com/uma/ingenieria-del-software",
    bestWuolahNotes: [
      {
        id: "pa-01",
        pdfPath: "pdfs/pa-01.pdf",
        isAvailable: true,
        fileSize: "3.2 KB",
        directVerified: true,
        title: "Manual Maestro de Programación Orientada a Objetos y TADs en C++",
        rating: 5.0,
        reviewsCount: 380,
        downloads: "3.5k",
        pages: 140,
        type: "Apuntes Completos",
        badge: "Top de la Carrera",
        uploader: "OOP_Wizard_UMA",
        description: "Considerado el mejor apunte de programación de 1º. Diagramas detallados del Heap y el Stack, implementación paso a paso de listas simplemente y doblemente enlazadas, y herencia con polimorfismo.",
        searchWuolahTerm: "Programacion Avanzada I C++ UMA apuntes completos POO"
      },
      {
        id: "pa-02",
        pdfPath: "pdfs/pa-02.pdf",
        isAvailable: true,
        fileSize: "2.8 KB",
        directVerified: true,
        title: "Colección de Exámenes Prácticos de Laboratorio y Proyectos Resueltos",
        rating: 4.9,
        reviewsCount: 260,
        downloads: "2.9k",
        pages: 115,
        type: "Prácticas & Exámenes",
        badge: "Prácticas 10/10",
        uploader: "Guille_Coder",
        description: "Enunciados de exámenes de código resueltos con clases bien encapsuladas, pruebas con asserts y sin pérdidas de memoria (comprobado con Valgrind).",
        searchWuolahTerm: "Programacion Avanzada I UMA examenes laboratorio practicas"
      },
      {
        id: "pa-03",
        pdfPath: "pdfs/pa-03.pdf",
        isAvailable: true,
        fileSize: "2.7 KB",
        directVerified: true,
        title: "Cheat Sheet: Sintaxis POO, Sobrecarga de Operadores y Punteros Inteligentes",
        rating: 4.9,
        reviewsCount: 180,
        downloads: "2.0k",
        pages: 11,
        type: "Formulario",
        badge: "Chuleta Rápida",
        uploader: "CodeNinja_UMA",
        description: "Estructura canónica de una clase C++, plantilla del operador de asignación, uso de std::unique_ptr y std::shared_ptr, y sintaxis de herencia virtual.",
        searchWuolahTerm: "Chuleta Programacion Avanzada I C++ UMA"
      }
    ]
  },
  {
    id: "110",
    code: "110",
    name: "Tecnología de Computadores",
    acronym: "TC",
    semester: 2,
    ects: 6,
    type: "Formación Básica",
    category: "hardware",
    difficulty: "Alta",
    passRate: "59%",
    color: "#eab308",
    icon: "cpu",
    umaGuideUrl: "https://www.uma.es/etsi-informatica/",
    summary: "Arquitectura interna del computador a nivel lógico y de hardware: sistemas de representación numérica, diseño de circuitos combinacionales y secuenciales, y procesador elemental.",
    topics: [
      "Representación de la información en computadores: Sistemas posicionales (binario, octal, hexadecimal)",
      "Aritmética binaria entera con y sin signo: Signo y magnitud, complemento a 1 y complemento a 2",
      "Representación de números reales en punto flotante: Estándar IEEE 754 de precisión simple y doble",
      "Álgebra de Boole, compuertas lógicas y minimización de funciones mediante Mapas de Karnaugh",
      "Diseño de circuitos combinacionales: Decodificadores, multiplexores, demultiplexores, sumadores y ALUs",
      "Elementos de memoria biestables (latches y flip-flops SR, D, JK, T; tablas de excitación y verdad)",
      "Circuitos secuenciales síncronos: Registros, contadores y diseño de máquinas de estados (Mealy y Moore)",
      "Estructura del computador elemental: Ruta de datos, bancos de registros, unidad de control y bus del sistema"
    ],
    examTips: "Los ejercicios de conversión y operaciones con el estándar IEEE 754 y el diseño de un contador síncrono mediante biestables JK son el 50% de la nota del examen final. Practica las tablas de excitación hasta dominarlas de memoria.",
    wuolahSearchQuery: "Tecnología de Computadores UMA Wuolah Informática",
    wuolahDirectUrl: "https://www.wuolah.com/uma/ingenieria-del-software",
    bestWuolahNotes: [
      {
        id: "tc-01",
        pdfPath: "pdfs/tc-01.pdf",
        isAvailable: true,
        fileSize: "3.2 KB",
        directVerified: true,
        title: "Apuntes Maestros de Tecnología de Computadores con Esquemas y Tablas",
        rating: 4.9,
        reviewsCount: 295,
        downloads: "3.0k",
        pages: 108,
        type: "Apuntes Completos",
        badge: "Top Valoración",
        uploader: "LogicGuru_UMA",
        description: "Explica desde cero la minimización por Karnaugh hasta la síntesis de autómatas Mealy/Moore con ejemplos claros y diagramas lógicos limpios.",
        searchWuolahTerm: "Tecnologia de Computadores UMA apuntes completos"
      },
      {
        id: "tc-02",
        pdfPath: "pdfs/tc-02.pdf",
        isAvailable: true,
        fileSize: "2.7 KB",
        directVerified: true,
        title: "Pack de Exámenes Resueltos: IEEE 754, Circuitos Secuenciales y Autómatas",
        rating: 5.0,
        reviewsCount: 280,
        downloads: "2.8k",
        pages: 125,
        type: "Exámenes Resueltos",
        badge: "Imprescindible",
        uploader: "HardwareBoy_Malaga",
        description: "Contiene ejercicios de examen resueltos paso a paso con la comprobación de estados equivalentes, tablas de transición y diagramas de tiempos de biestables.",
        searchWuolahTerm: "Tecnologia Computadores UMA examenes resueltos parciales"
      },
      {
        id: "tc-03",
        pdfPath: "pdfs/tc-03.pdf",
        isAvailable: true,
        fileSize: "2.7 KB",
        directVerified: true,
        title: "Formulario Completo: Tabla IEEE 754, Tablas de Excitación Biestables y Leyes de Boole",
        rating: 4.8,
        reviewsCount: 130,
        downloads: "1.6k",
        pages: 6,
        type: "Formulario",
        badge: "Chuleta Rápida",
        uploader: "BitMaster",
        description: "Todo el formulario esencial condensado: fórmulas de bias/sesgo para IEEE 754, tablas de excitación de biestables D, JK, T y teoremas de De Morgan.",
        searchWuolahTerm: "Formulario Tecnologia Computadores UMA"
      }
    ]
  }
];

// Consejos clave de supervivencia para 1º año en la UMA ETSI Informática
const WUOLAH_SURVIVAL_TIPS = [
  {
    title: "Filtrado Cruzado Inteligente",
    description: "En 1º de carrera, muchas asignaturas son comunes con el Grado en Ingeniería Informática y Grado en Ingeniería de Computadores de la UMA. Si un apunte en Wuolah para Software tiene pocas descargas, búscalo en la sección de Grado en Ingeniería Informática: ¡los profesores y temarios son idénticos!"
  },
  {
    title: "Prioriza Exámenes y Formularios",
    description: "Los exámenes en la ETSI Informática siguen patrones muy consistentes año tras año. Empezar a estudiar resolviendo exámenes de convocatorias pasadas desde la mitad del cuatrimestre es la técnica más efectiva para aprobar a la primera."
  },
  {
    title: "Verifica las Estrellas y Comentarios",
    description: "En Wuolah, fíjate siempre en documentos con más de 4.8 estrellas y comentarios recientes. Los apuntes que llevan la etiqueta 'Matrícula de Honor' o que tienen esquemas a color suelen ser los más ordenados y fiables."
  },
  {
    title: "Prácticas de Laboratorio (SageMath, C++, C)",
    description: "No descuides las prácticas de laboratorio en asignaturas como Matemática Discreta o Introducción a la Programación. Aprobar el laboratorio suele ser condición indispensable para superar la asignatura en la convocatoria ordinaria."
  }
];
